// Searchable worship-song catalog: titles and authors/worship teams only
// (factual metadata — no lyrics or charts). Entries with a `chart` id link to
// the in-app chord chart in the Song Library.

export interface CatalogSong {
  id: string;
  title: string;
  author: string;
  category: "modern" | "traditional";
  chart?: string; // id into SONGS (src/lib/songs.ts)
}

// [title, author, chartId?]
type Row = [string, string, string?];

const MODERN: Row[] = [
  ["Oceans (Where Feet May Fail)", "Hillsong UNITED"],
  ["What a Beautiful Name", "Hillsong Worship", "what-a-beautiful-name"],
  ["King of Kings", "Hillsong Worship"],
  ["Who You Say I Am", "Hillsong Worship"],
  ["Cornerstone", "Hillsong Worship", "cornerstone"],
  ["Mighty to Save", "Hillsong Worship"],
  ["Hosanna", "Hillsong UNITED"],
  ["Still", "Hillsong Worship"],
  ["The Stand", "Hillsong UNITED"],
  ["So Will I (100 Billion X)", "Hillsong UNITED"],
  ["Broken Vessels (Amazing Grace)", "Hillsong Worship"],
  ["O Praise the Name (Anastasis)", "Hillsong Worship"],
  ["This I Believe (The Creed)", "Hillsong Worship"],
  ["Forever Reign", "Hillsong Worship"],
  ["New Wine", "Hillsong Worship"],
  ["Another in the Fire", "Hillsong UNITED"],
  ["Shout to the Lord", "Darlene Zschech · Hillsong"],
  ["A Thousand Hallelujahs", "Brooke Ligertwood"],
  ["Honey in the Rock", "Brooke Ligertwood & Brandon Lake"],
  ["O Come to the Altar", "Elevation Worship"],
  ["Do It Again", "Elevation Worship"],
  ["Graves Into Gardens", "Elevation Worship & Brandon Lake"],
  ["The Blessing", "Kari Jobe, Cody Carnes & Elevation Worship"],
  ["Same God", "Elevation Worship"],
  ["Praise", "Elevation Worship"],
  ["Trust in God", "Elevation Worship"],
  ["LION", "Elevation Worship"],
  ["More Than Able", "Elevation Worship & Maverick City"],
  ["Here Again", "Elevation Worship"],
  ["Resurrecting", "Elevation Worship"],
  ["See a Victory", "Elevation Worship"],
  ["RATTLE!", "Elevation Worship"],
  ["Goodness of God", "Jenn Johnson · Bethel Music"],
  ["Reckless Love", "Cory Asbury · Bethel Music"],
  ["No Longer Slaves", "Bethel Music"],
  ["Raise a Hallelujah", "Bethel Music"],
  ["Ever Be", "Bethel Music"],
  ["Stand in Your Love", "Josh Baldwin · Bethel Music"],
  ["King of My Heart", "John Mark & Sarah McMillan"],
  ["The Father's House", "Cory Asbury"],
  ["Living Hope", "Phil Wickham"],
  ["This Is Amazing Grace", "Phil Wickham"],
  ["House of the Lord", "Phil Wickham"],
  ["Battle Belongs", "Phil Wickham"],
  ["Great Things", "Phil Wickham"],
  ["Hymn of Heaven", "Phil Wickham"],
  ["How Great Is Our God", "Chris Tomlin"],
  ["Amazing Grace (My Chains Are Gone)", "Chris Tomlin"],
  ["Our God", "Chris Tomlin"],
  ["Whom Shall I Fear (God of Angel Armies)", "Chris Tomlin"],
  ["Holy Forever", "Chris Tomlin"],
  ["Jesus Messiah", "Chris Tomlin"],
  ["Indescribable", "Chris Tomlin"],
  ["Good Good Father", "Pat Barrett · Housefires"],
  ["Build My Life", "Pat Barrett · Housefires"],
  ["10,000 Reasons (Bless the Lord)", "Matt Redman", "10000-reasons"],
  ["Blessed Be Your Name", "Matt & Beth Redman"],
  ["The Heart of Worship", "Matt Redman"],
  ["You Never Let Go", "Matt & Beth Redman"],
  ["Way Maker", "Sinach"],
  ["Jireh", "Maverick City Music & Elevation Worship"],
  ["Promises", "Maverick City Music"],
  ["Firm Foundation (He Won't)", "Cody Carnes · Maverick City"],
  ["Million Little Miracles", "Maverick City & Elevation Worship"],
  ["Man of Your Word", "Maverick City Music"],
  ["Refiner", "Maverick City Music"],
  ["Talking to Jesus", "Maverick City & Brandon Lake"],
  ["Run to the Father", "Cody Carnes"],
  ["Christ Be Magnified", "Cody Carnes"],
  ["Nothing Else", "Cody Carnes"],
  ["Glorious Day", "Kristian Stanfill · Passion"],
  ["What He's Done", "Passion"],
  ["Great Are You Lord", "All Sons & Daughters"],
  ["Build Your Kingdom Here", "Rend Collective"],
  ["My Lighthouse", "Rend Collective"],
  ["Death Was Arrested", "North Point Worship"],
  ["Tremble", "Mosaic MSC"],
  ["Yes I Will", "Vertical Worship"],
  ["Lord, I Need You", "Matt Maher"],
  ["Because He Lives (Amen)", "Matt Maher"],
  ["I Speak Jesus", "Charity Gayle"],
  ["Gratitude", "Brandon Lake"],
  ["Praise You Anywhere", "Brandon Lake"],
  ["Holy Spirit", "Bryan & Katie Torwalt"],
  ["Set a Fire", "Will Reagan · United Pursuit"],
  ["How He Loves", "John Mark McMillan"],
  ["Come As You Are", "Crowder"],
  ["Everlasting God", "Brenton Brown"],
  ["Surrounded (Fight My Battles)", "UPPERROOM · Michael W. Smith"],
  ["Worthy of It All", "David Brymer · UPPERROOM"],
  ["Agnus Dei", "Michael W. Smith"],
  ["Open the Eyes of My Heart", "Paul Baloche"],
  ["Here I Am to Worship", "Tim Hughes"],
  ["Above All", "Paul Baloche & Lenny LeBlanc"],
  ["Revelation Song", "Jennie Lee Riddle · Kari Jobe"],
  ["Days of Elijah", "Robin Mark"],
  ["How Deep the Father's Love for Us", "Stuart Townend"],
  ["In Christ Alone", "Keith Getty & Stuart Townend", "in-christ-alone"],
  ["The Power of the Cross", "Keith & Kristyn Getty"],
  ["By Faith", "Keith & Kristyn Getty"],
  ["Christ Our Hope in Life and Death", "Keith Getty & Matt Papa"],
  ["His Mercy Is More", "Matt Boswell & Matt Papa"],
  ["Yet Not I but Through Christ in Me", "CityAlight"],
  ["Only a Holy God", "CityAlight"],
  ["Ancient of Days", "CityAlight"],
  ["Behold Our God", "Sovereign Grace Music"],
  ["The Lion and the Lamb", "Leeland · Big Daddy Weave"],
  ["Forever", "Kari Jobe"],
  ["My Jesus", "Anne Wilson"],
  ["You Are My King (Amazing Love)", "Billy Foote"],
  ["Draw Me Close", "Kelly Carpenter"],
  ["Give Us Clean Hands", "Charlie Hall"],
  ["God So Loved", "We The Kingdom"],
  ["Holy Water", "We The Kingdom"],
];

const TRADITIONAL: Row[] = [
  ["Amazing Grace", "John Newton", "amazing-grace"],
  ["Be Thou My Vision", "Irish trad., tr. Byrne & Hull", "be-thou-my-vision"],
  ["Come Thou Fount of Every Blessing", "Robert Robinson", "come-thou-fount"],
  ["Holy, Holy, Holy", "Reginald Heber", "holy-holy-holy"],
  ["It Is Well With My Soul", "Horatio Spafford", "it-is-well"],
  ["Great Is Thy Faithfulness", "Thomas Chisholm", "great-is-thy-faithfulness"],
  ["Blessed Assurance", "Fanny Crosby", "blessed-assurance"],
  ["The Old Rugged Cross", "George Bennard", "old-rugged-cross"],
  ["I Surrender All", "Judson Van DeVenter", "i-surrender-all"],
  ["Turn Your Eyes Upon Jesus", "Helen Lemmel", "turn-your-eyes"],
  ["'Tis So Sweet to Trust in Jesus", "Louisa Stead", "tis-so-sweet"],
  ["Leaning on the Everlasting Arms", "Elisha Hoffman", "everlasting-arms"],
  ["Nothing but the Blood", "Robert Lowry", "nothing-but-the-blood"],
  ["Crown Him with Many Crowns", "Matthew Bridges", "crown-him"],
  ["Doxology (Praise God From Whom All Blessings Flow)", "Thomas Ken", "doxology"],
  ["How Great Thou Art", "Stuart K. Hine", "how-great-thou-art"],
  ["A Mighty Fortress Is Our God", "Martin Luther"],
  ["All Hail the Power of Jesus' Name", "Edward Perronet"],
  ["And Can It Be", "Charles Wesley"],
  ["O For a Thousand Tongues to Sing", "Charles Wesley"],
  ["Christ the Lord Is Risen Today", "Charles Wesley"],
  ["Hark! The Herald Angels Sing", "Charles Wesley"],
  ["Love Divine, All Loves Excelling", "Charles Wesley"],
  ["Come, Thou Long Expected Jesus", "Charles Wesley"],
  ["Joy to the World", "Isaac Watts"],
  ["When I Survey the Wondrous Cross", "Isaac Watts"],
  ["At the Cross (Alas! And Did My Savior Bleed)", "Isaac Watts"],
  ["O God, Our Help in Ages Past", "Isaac Watts"],
  ["Silent Night", "Joseph Mohr & Franz Gruber"],
  ["O Come, All Ye Faithful", "John Francis Wade"],
  ["O Holy Night", "Adolphe Adam"],
  ["What Child Is This", "William Chatterton Dix"],
  ["O Come, O Come, Emmanuel", "Latin hymn, tr. John Mason Neale"],
  ["Rock of Ages", "Augustus Toplady"],
  ["Just As I Am", "Charlotte Elliott"],
  ["Softly and Tenderly", "Will Thompson"],
  ["Pass Me Not, O Gentle Savior", "Fanny Crosby"],
  ["To God Be the Glory", "Fanny Crosby"],
  ["Near the Cross", "Fanny Crosby"],
  ["Redeemed, How I Love to Proclaim It", "Fanny Crosby"],
  ["Praise to the Lord, the Almighty", "Joachim Neander"],
  ["Immortal, Invisible, God Only Wise", "Walter Chalmers Smith"],
  ["Fairest Lord Jesus", "German traditional"],
  ["Be Still, My Soul", "Katharina von Schlegel"],
  ["Abide with Me", "Henry Lyte"],
  ["My Hope Is Built (The Solid Rock)", "Edward Mote"],
  ["Standing on the Promises", "R. Kelso Carter"],
  ["Trust and Obey", "John Sammis"],
  ["What a Friend We Have in Jesus", "Joseph Scriven"],
  ["Sweet Hour of Prayer", "William Walford"],
  ["I Need Thee Every Hour", "Annie Hawks"],
  ["Take My Life and Let It Be", "Frances Havergal"],
  ["Have Thine Own Way, Lord", "Adelaide Pollard"],
  ["There Is a Fountain", "William Cowper"],
  ["Jesus Paid It All", "Elvina Hall"],
  ["The Church's One Foundation", "Samuel Stone"],
  ["In the Garden", "C. Austin Miles"],
  ["His Eye Is on the Sparrow", "Civilla Martin"],
  ["I Love to Tell the Story", "Katherine Hankey"],
  ["Count Your Blessings", "Johnson Oatman"],
  ["He Leadeth Me", "Joseph Gilmore"],
  ["All Creatures of Our God and King", "Francis of Assisi, tr. William Draper"],
  ["For the Beauty of the Earth", "Folliott Pierpoint"],
  ["This Is My Father's World", "Maltbie Babcock"],
  ["O Worship the King", "Robert Grant"],
  ["Guide Me, O Thou Great Jehovah", "William Williams"],
  ["When We All Get to Heaven", "Eliza Hewitt"],
  ["Higher Ground", "Johnson Oatman"],
  ["Are You Washed in the Blood", "Elisha Hoffman"],
  ["There Is Power in the Blood", "Lewis Jones"],
  ["Down at the Cross (Glory to His Name)", "Elisha Hoffman"],
  ["Grace Greater Than Our Sin", "Julia Johnston"],
  ["My Faith Looks Up to Thee", "Ray Palmer"],
  ["Savior, Like a Shepherd Lead Us", "Dorothy Thrupp"],
  ["Man of Sorrows (Hallelujah! What a Savior)", "Philip Bliss"],
  ["Nearer, My God, to Thee", "Sarah Adams"],
  ["I'll Fly Away", "Albert Brumley"],
  ["Victory in Jesus", "Eugene Bartlett"],
  ["How Firm a Foundation", "'K' in Rippon's Selection, 1787"],
];

function slug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
}

function expand(rows: Row[], category: "modern" | "traditional"): CatalogSong[] {
  return rows.map(([title, author, chart]) => ({
    id: `${category}-${slug(title)}`,
    title,
    author,
    category,
    ...(chart ? { chart } : {}),
  }));
}

export const CATALOG: CatalogSong[] = [...expand(MODERN, "modern"), ...expand(TRADITIONAL, "traditional")];

export function searchCatalog(query: string, category?: "modern" | "traditional"): CatalogSong[] {
  const q = query.trim().toLowerCase();
  return CATALOG.filter((s) => {
    if (category && s.category !== category) return false;
    if (!q) return true;
    return s.title.toLowerCase().includes(q) || s.author.toLowerCase().includes(q);
  });
}
